### PR TITLE
[SOL-1326] Create new product category to support enrollment codes

### PR DESCRIPTION
**Pull request by vkaracic**
https://openedx.atlassian.net/browse/SOL-1326

- [x] add Client model
- [x] create a ProductClass in a migration
- [x] add ProductAttributes to the created ProductClass and create a category
- [x] create default edX partner
- [x] write tests

This is a continuation of https://github.com/vkaracic/ecommerce/pull/8 closed due to a rebase mistake.

@mjfrey I've addressed your comments on the last PR here.

### CODE REVIEW

**Comment by mjfrey** [comment]
:+1: 
Looks good.

**Comment by vkaracic** [comment]
@marjev @dsego can you guys take a quick look at this code?

**Comment by dsego** [comment]
:+1:

**Comment by marjev** [comment]
:+1:

**Pull request merged**
